"""agrega columnas de contexto del PDT, nombre de sector y presupuesto

Revision ID: 122e94509b80
Revises: d6f307358ef7
Create Date: 2026-09-23 16:58:30.518556
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '122e94509b80'
down_revision: Union[str, None] = 'd6f307358ef7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meta', sa.Column('entidad_territorial', sa.Text(), nullable=True))
    op.add_column('meta', sa.Column('nombre_plan', sa.Text(), nullable=True))
    op.add_column('meta', sa.Column('fecha_creacion_plan', sa.Date(), nullable=True))
    op.add_column('meta', sa.Column('linea_estrategica', sa.Text(), nullable=True))
    op.add_column('meta', sa.Column('codigo_sector', sa.String(length=10), nullable=True))
    op.add_column('meta', sa.Column('sector', sa.Text(), nullable=True))
    op.add_column('meta', sa.Column('codigo_programa', sa.String(length=10), nullable=True))
    op.add_column('meta', sa.Column('programa', sa.Text(), nullable=True))
    op.add_column('meta', sa.Column('codigo_ods', sa.String(length=10), nullable=True))
    op.add_column('meta', sa.Column('ods', sa.Text(), nullable=True))
    op.add_column('meta', sa.Column('tipo_acumulacion', sa.String(length=50), nullable=True))
    op.add_column('rubro', sa.Column('nombre_sector_ccpet', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rubro', 'nombre_sector_ccpet')
    op.drop_column('meta', 'tipo_acumulacion')
    op.drop_column('meta', 'ods')
    op.drop_column('meta', 'codigo_ods')
    op.drop_column('meta', 'programa')
    op.drop_column('meta', 'codigo_programa')
    op.drop_column('meta', 'sector')
    op.drop_column('meta', 'codigo_sector')
    op.drop_column('meta', 'linea_estrategica')
    op.drop_column('meta', 'fecha_creacion_plan')
    op.drop_column('meta', 'nombre_plan')
    op.drop_column('meta', 'entidad_territorial')
    # ### end Alembic commands ###
