"""amplia meta.unidad_medida a texto libre

Revision ID: d6f307358ef7
Revises: 3cba947a3f5d
Create Date: 2026-09-18 23:03:38.220053
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd6f307358ef7'
down_revision: Union[str, None] = '3cba947a3f5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meta', 'unidad_medida',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meta', 'unidad_medida',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
    # ### end Alembic commands ###
