"""esquema inicial

Revision ID: e96e8c9fd07d
Revises: 
Create Date: 2026-09-10 18:36:49.896000
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e96e8c9fd07d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corte',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vigencia', sa.SmallInteger(), nullable=False),
    sa.Column('fecha_corte', sa.Date(), nullable=False),
    sa.Column('estado', sa.Enum('BORRADOR', 'REGISTRADO', name='estado_corte'), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ux_corte_borrador_por_vigencia', 'corte', ['vigencia'], unique=True, postgresql_where=sa.text("estado = 'BORRADOR'"), sqlite_where=sa.text("estado = 'BORRADOR'"))
    op.create_table('archivo_fuente',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('corte_id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.Enum('PDT', 'EJECUCION', 'PROYECTOS', name='tipo_archivo_fuente'), nullable=False),
    sa.Column('nombre_archivo', sa.String(length=255), nullable=False),
    sa.Column('filas_reconocidas', sa.Integer(), nullable=False),
    sa.Column('reutilizado', sa.Boolean(), nullable=False),
    sa.Column('corte_origen_id', sa.Uuid(), nullable=True),
    sa.Column('fecha_carga', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['corte_id'], ['corte.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['corte_origen_id'], ['corte.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('corte_id', 'tipo', name='ux_archivo_por_tipo')
    )
    op.create_index(op.f('ix_archivo_fuente_corte_id'), 'archivo_fuente', ['corte_id'], unique=False)
    op.create_table('meta',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('corte_id', sa.Uuid(), nullable=False),
    sa.Column('cod_indicador_producto', sa.String(length=9), nullable=False),
    sa.Column('cod_indicador_sistp', sa.String(length=20), nullable=True),
    sa.Column('codigo_producto_mga', sa.String(length=7), nullable=True),
    sa.Column('nombre_producto', sa.Text(), nullable=True),
    sa.Column('unidad_medida', sa.String(length=120), nullable=True),
    sa.Column('meta_cuatrienio', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('es_principal', sa.Boolean(), nullable=False),
    sa.Column('bpin_relacionados', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['corte_id'], ['corte.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_meta_cruce', 'meta', ['corte_id', 'cod_indicador_producto'], unique=False)
    op.create_table('proyecto',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('corte_id', sa.Uuid(), nullable=False),
    sa.Column('bpin', sa.String(length=20), nullable=True),
    sa.Column('nombre_proyecto', sa.Text(), nullable=True),
    sa.Column('indicador_producto_raw', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['corte_id'], ['corte.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rubro',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('corte_id', sa.Uuid(), nullable=False),
    sa.Column('codigo_rubro_nivel', sa.String(length=150), nullable=False),
    sa.Column('codigo_rubro_ccpet', sa.String(length=150), nullable=True),
    sa.Column('codigo_rubro_completo', sa.String(length=255), nullable=True),
    sa.Column('codigo_sector_ccpet', sa.String(length=2), nullable=True),
    sa.Column('codigo_producto_ccpet', sa.String(length=7), nullable=True),
    sa.Column('cod_indicador_producto', sa.String(length=9), nullable=True),
    sa.Column('codigo_tipo_gasto', sa.String(length=20), nullable=True),
    sa.Column('nombre_financiacion', sa.String(length=255), nullable=True),
    sa.Column('ultimo_nivel', sa.Boolean(), nullable=False),
    sa.Column('apropiacion_definitiva', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('disponibilidad_acumulada', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('compromiso_acumulado', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('obligacion_acumulada', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('pago_acumulado', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['corte_id'], ['corte.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('corte_id', 'codigo_rubro_nivel', name='ux_rubro_nivel')
    )
    op.create_index('ix_rubro_cruce', 'rubro', ['corte_id', 'cod_indicador_producto'], unique=False)
    op.create_table('contrato',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('corte_id', sa.Uuid(), nullable=False),
    sa.Column('proyecto_id', sa.Uuid(), nullable=True),
    sa.Column('numero_contrato', sa.String(length=120), nullable=True),
    sa.Column('llave_sustituta', sa.String(length=64), nullable=True),
    sa.Column('objeto', sa.Text(), nullable=True),
    sa.Column('modalidad_seleccion', sa.String(length=120), nullable=True),
    sa.Column('tipo_gasto', sa.String(length=20), nullable=True),
    sa.Column('nit_contratista', sa.String(length=20), nullable=True),
    sa.Column('nombre_contratista', sa.Text(), nullable=True),
    sa.Column('valor_contrato', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('valor_pagado', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('bpin', sa.String(length=20), nullable=True),
    sa.Column('cod_indicador_producto', sa.String(length=9), nullable=True),
    sa.ForeignKeyConstraint(['corte_id'], ['corte.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyecto.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contrato_cruce', 'contrato', ['corte_id', 'cod_indicador_producto'], unique=False)
    op.create_table('meta_programacion_fisica',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('meta_id', sa.Uuid(), nullable=False),
    sa.Column('anio', sa.SmallInteger(), nullable=False),
    sa.Column('valor_programado', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['meta_id'], ['meta.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meta_id', 'anio', name='ux_prog_fisica_meta_anio')
    )
    op.create_table('programacion_financiera',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('meta_id', sa.Uuid(), nullable=True),
    sa.Column('proyecto_id', sa.Uuid(), nullable=True),
    sa.Column('fuente', sa.String(length=120), nullable=True),
    sa.Column('anio', sa.SmallInteger(), nullable=False),
    sa.Column('valor_programado', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['meta_id'], ['meta.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyecto.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_prog_financiera_meta', 'programacion_financiera', ['meta_id'], unique=False)
    op.create_table('proyecto_indicador',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('proyecto_id', sa.Uuid(), nullable=False),
    sa.Column('cod_indicador_producto', sa.String(length=9), nullable=False),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyecto.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proyecto_id', 'cod_indicador_producto', name='ux_proyecto_indicador')
    )
    op.create_index('ix_proyecto_indicador_cod', 'proyecto_indicador', ['cod_indicador_producto'], unique=False)
    op.create_table('registro_presupuestal',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contrato_id', sa.Uuid(), nullable=False),
    sa.Column('rubro_id', sa.Uuid(), nullable=True),
    sa.Column('codigo_rubro_crudo', sa.String(length=255), nullable=True),
    sa.Column('numero_cdp', sa.String(length=60), nullable=True),
    sa.Column('fecha_cdp', sa.Date(), nullable=True),
    sa.Column('valor_cdp', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('numero_registro', sa.String(length=60), nullable=True),
    sa.Column('fecha_registro', sa.Date(), nullable=True),
    sa.Column('valor_registro_ptal', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('valor_pagos', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['contrato_id'], ['contrato.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rubro_id'], ['rubro.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registro_presupuestal_contrato_id'), 'registro_presupuestal', ['contrato_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registro_presupuestal_contrato_id'), table_name='registro_presupuestal')
    op.drop_table('registro_presupuestal')
    op.drop_index('ix_proyecto_indicador_cod', table_name='proyecto_indicador')
    op.drop_table('proyecto_indicador')
    op.drop_index('ix_prog_financiera_meta', table_name='programacion_financiera')
    op.drop_table('programacion_financiera')
    op.drop_table('meta_programacion_fisica')
    op.drop_index('ix_contrato_cruce', table_name='contrato')
    op.drop_table('contrato')
    op.drop_index('ix_rubro_cruce', table_name='rubro')
    op.drop_table('rubro')
    op.drop_table('proyecto')
    op.drop_index('ix_meta_cruce', table_name='meta')
    op.drop_table('meta')
    op.drop_index(op.f('ix_archivo_fuente_corte_id'), table_name='archivo_fuente')
    op.drop_table('archivo_fuente')
    op.drop_index('ux_corte_borrador_por_vigencia', table_name='corte', postgresql_where=sa.text("estado = 'BORRADOR'"), sqlite_where=sa.text("estado = 'BORRADOR'"))
    op.drop_table('corte')
    # ### end Alembic commands ###

    # Ajuste manual: autogenerate NO elimina los tipos ENUM de PostgreSQL al
    # borrar la tabla que los usa. Sin esto, un segundo `upgrade` tras un
    # `downgrade` falla con "type ... already exists".
    bind = op.get_bind()
    sa.Enum(name='estado_corte').drop(bind, checkfirst=True)
    sa.Enum(name='tipo_archivo_fuente').drop(bind, checkfirst=True)
